version: '3'
services:
    nginx:
        container_name: ${CONTAINER_NAME_NGINX}
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
            - ./data/logs/:/var/log/nginx/
        depends_on:
            - php
        external_links:
            - db
        restart: always

    php:
        container_name: ${CONTAINER_NAME_PHP}
        build:
            context: ./web
            dockerfile: app.docker
        volumes:
            - ./src:/var/www/html
        restart: always

    db:
        image: mariadb
        container_name: ${CONTAINER_NAME_DB}
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - ./data/db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always
